window.keyMapping = [
  // ['תאריך קליטה', 'joinedDate'],
  ['כוח', 'division'],
  ['שם פרטי', 'firstName'],
  ['שם משפחה', 'lastName'],
  ['טלפון נייד', 'mobile'],
  ['טלפון עיקרי', 'mainPhone'],
  // ['אימון אפריל 2021', 'april21Training'],
  ['שם תפקיד בעץ מבנה', 'position'],
  ['דרגה', 'rank'],
  ['מספר אישי', 'idfId'],
  ['מספר זהות', 'id'],
  ['גיל', 'age'],
  ['תאריך לידה', 'dateOfBirth'],
  ['כתובת מייל דוא"ל', 'email'],
  ['רובאי', 'rifleRank'],
  ['פרופיל', 'profile'],
  ['מקצוע', 'armyJob'],
  ['מקצוע אזרחי', 'job'],
  ['רשיון מחושב', 'drivingLicense'],
  ['שם דרגה רכב 4 גלגלי', 'rank4Wheel'],
  ['רשיון היתר 1', 'licence1'],
  ['רשיון היתר 2', 'licence2'],
  ['שם בן זוג', 'spouseName'],
  ['מספר ילדים', 'numChildren'],
  ['כתובת', 'address'],
  ['הכשרה 1', 'training1'],
  ['הכשרה 2', 'training2'],
  ['הכשרה 3', 'training3'],
  ['הכשרה 4', 'training4'],
  ['הכשרה 5', 'training5'],
  ['הכשרה 6', 'training6'],
  ['הכשרה 7', 'training7'],
  ['הכשרה 8', 'training8'],
  ['הכשרה 9', 'training9'],
  ['הכשרה 10', 'training10'],
  ['יתר הכשרות', 'trainingRest'],
];
